#import libarraies
import streamlit as st

import torch
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator

import rasterio
from rasterio.windows import Window
from rasterio.windows import from_bounds
from rasterio.mask import mask

import cv2
import matplotlib.pyplot as plt
import numpy as np
from rasterstats import zonal_stats

import laspy

import json
import geopandas as gpd
from shapely.geometry import box
from shapely.geometry import Polygon

import pydeck as pdk

def generate_container_segment_masks(
    user_selected_image_path, 
    sam_model_path,
    points_per_side=32,
    pred_iou_thresh=0.80,
    stability_score_thresh=0.80,
    min_mask_region_area=500):
    """
    Generate segmentation masks for the selected image using the Segment Anything Model.

    The function reads the selected RGB image tile, loads the SAM ViT-B model from
    the provided checkpoint, and applies automatic mask generation to identify
    possible container-like objects.

    Parameters
    ----------
    user_selected_image_path : str or Path
        Path to the selected cropped GeoTIFF image or image tile.
    sam_model_path : str or Path
        Path to the Segment Anything model checkpoint file.
    points_per_side : int, optional
        Number of points sampled along one side of the image for mask generation.
    pred_iou_thresh : float, optional
        Predicted IoU threshold used by SAM to filter low-quality masks.
    stability_score_thresh : float, optional
        Stability score threshold used to remove unstable masks.
    min_mask_region_area : int, optional
        Minimum mask region area, in pixels, used to remove very small segments.

    Returns
    -------
    list
        List of mask dictionaries generated by SAM.
    """
    
    with rasterio.open(user_selected_image_path) as src:
        user_selected_image = src.read([1, 2, 3]).transpose([1, 2, 0])
        
    #clear GPU memory
    torch.cuda.empty_cache()

    #load SAM ViT-B pretrained model
    sam = sam_model_registry["vit_b"](checkpoint=sam_model_path)
    sam.to("cuda" if torch.cuda.is_available() else "cpu")

    #model configuration
    mask_generator = SamAutomaticMaskGenerator(
        model=sam,
        points_per_side=points_per_side,
        pred_iou_thresh=pred_iou_thresh,
        stability_score_thresh=stability_score_thresh,
        min_mask_region_area=min_mask_region_area,
    )
    
    # mask_generator = SamAutomaticMaskGenerator(
    #     model=sam,
    #     points_per_side=64,
    #     crop_n_layers=1,
    #     crop_n_points_downscale_factor=2,
    #     pred_iou_thresh=0.90,
    #     stability_score_thresh=0.90,
    #     min_mask_region_area=1000,
    # )

    masks = mask_generator.generate(user_selected_image)
    
    return masks

def convert_masks_to_boxes(masks):    
    """
    Convert SAM segmentation masks into rotated bounding boxes.

    For each segmentation mask, the function extracts the largest contour and
    fits a minimum-area rotated rectangle around it. The resulting boxes are
    stored together with basic shape attributes used later for filtering.

    Parameters
    ----------
    masks : list
        List of mask dictionaries returned by the SAM automatic mask generator.

    Returns
    -------
    list of dict
        List of rotated bounding boxes and their attributes, including mask area,
        aspect ratio, box width, and box height.
    """
    boxes = []

    for mask in masks:
        # if (mask['area'] < 15000) and (mask['area'] > 2000):
            m = mask['segmentation'].astype(np.uint8)
            
            contours, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            if not contours:
                continue
            cnt = max(contours, key=cv2.contourArea)
            rect = cv2.minAreaRect(cnt)

            (cx, cy), (bw, bh), angle = rect
            rect_global = ((cx, cy), (bw, bh), angle)

            # Store box with shape attributes for later filtering
            if min(bw, bh) > 0:
                boxes.append({
                    'rect': rect_global,
                    'area': mask['area'],
                    'aspect_ratio': max(bw, bh) / min(bw, bh),
                    'box_w': bw,
                    'box_h': bh
                })
        
    return boxes

def convert_boxes_to_geojson(boxes, user_selected_aoi_path, output_path):
    """
    Convert rotated bounding boxes from image pixel coordinates to GeoJSON polygons.

    The function uses the geotransform of the selected cropped image to convert
    each bounding box corner from pixel coordinates into map coordinates. The
    converted polygons are saved as a GeoJSON FeatureCollection.

    Parameters
    ----------
    boxes : list of dict
        List of rotated bounding boxes generated from segmentation masks.
    user_selected_aoi_path : str or Path
        Path to the cropped GeoTIFF image used for detection.
    output_path : str or Path
        Path where the output GeoJSON file will be saved.

    Returns
    -------
    None
        The GeoJSON file is written directly to output_path.
    """
    with rasterio.open(user_selected_aoi_path) as src:
        transform = src.transform
    
    def pixel_to_geo(px, py, transform):
        """
        Convert a single pixel coordinate to map coordinates using a raster transform.
        """
        gx = transform.c + float(px) * transform.a
        gy = transform.f + float(py) * transform.e
        return gx, gy

    features = []
    for i, b in enumerate(boxes):
        box_points = cv2.boxPoints(b['rect'])

        geo_points = []
        for px, py in box_points:
            gx, gy = pixel_to_geo(px, py, transform)
            geo_points.append([gx, gy])
        geo_points.append(geo_points[0])  # close polygon

        feature = {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [geo_points]
            },
            "properties": {
                "id": int(i),
                "area_px": float(round(b['area'], 2)),
                "aspect_ratio": float(round(b['aspect_ratio'], 2)),
                # "zone": "ship" if (9000 < b['rect'][0][0] < 10000 and
                #                    1000 < b['rect'][0][1] < 6000) else "yard"
            }
        }
        features.append(feature)

    geojson = {
        "type": "FeatureCollection",
        "crs": {"type": "name", "properties": {"name": "EPSG:32631"}},
        "features": features
    }

    output_path = output_path
    with open(output_path, 'w') as f:
        json.dump(geojson, f)
        

def pixel_bounds_to_map_bounds(tiff_path, bounds):
    """
    Convert TIFF pixel bounds into map coordinate bounds.

    The function creates a rasterio window from pixel coordinates and converts that
    window into real-world map coordinates using the TIFF geotransform.

    Parameters
    ----------
    tiff_path : str or pathlib.Path
        Path to the source TIFF image.
    bounds : dict
        Pixel bounds dictionary containing left, top, width, and height.

    Returns
    -------
    dict
        Dictionary containing xmin, ymin, xmax, ymax, and crs for the selected area.
    """

    left = int(bounds["left"])
    top = int(bounds["top"])
    width = int(bounds["width"])
    height = int(bounds["height"])

    with rasterio.open(tiff_path) as src:
        window = Window(left, top, width, height)

        # Returns bounds in the TIFF CRS: left, bottom, right, top
        xmin, ymin, xmax, ymax = src.window_bounds(window)

        return {
            "xmin": xmin,
            "ymin": ymin,
            "xmax": xmax,
            "ymax": ymax,
            "crs": src.crs
        }

def filter_las_by_map_bounds(las_path, output_las_path, map_bounds, zmax=81):
    """
    Filter a LAS point cloud using map coordinate bounds.

    The function keeps only LiDAR points whose x and y coordinates fall inside the
    selected map bounds. An optional maximum z-value can also be applied to remove
    very high points.

    Parameters
    ----------
    las_path : str or pathlib.Path
        Path to the input LAS file.
    output_las_path : str or pathlib.Path
        Path where the filtered LAS file should be saved.
    map_bounds : dict
        Dictionary containing xmin, ymin, xmax, and ymax map coordinates.
    zmax : int or float, optional
        Maximum z-value to retain. If None, no z filtering is applied.

    Returns
    -------
    str or pathlib.Path
        Path to the saved filtered LAS file.
    """
    las = laspy.read(las_path)

    x = las.x
    y = las.y
    z = las.z

    mask = (
        (x >= map_bounds["xmin"]) &
        (x <= map_bounds["xmax"]) &
        (y >= map_bounds["ymin"]) &
        (y <= map_bounds["ymax"])
    )

    if zmax is not None:
        mask &= (z <= zmax)

    cropped_las = laspy.LasData(las.header)
    cropped_las.points = las.points[mask]

    cropped_las.write(output_las_path)

    return output_las_path

def add_las_elevation_stats(filtered_las_path, geojson_path=None, gdf=None):
    """
    Add LiDAR elevation statistics to detected container polygons.

    The function reads a filtered LAS point cloud and assigns each LiDAR point to
    the polygon it falls within. It then calculates elevation statistics for each
    polygon, such as point count, minimum elevation, maximum elevation, mean,
    median, and standard deviation.

    Parameters
    ----------
    filtered_las_path : str or Path
        Path to the LAS file that has already been filtered to the selected image area.
    geojson_path : str or Path, optional
        Path to the GeoJSON file containing detected container polygons.
        Used when gdf is not supplied.
    gdf : geopandas.GeoDataFrame, optional
        GeoDataFrame containing detected container polygons. Used instead of
        reading from geojson_path.

    Returns
    -------
    geopandas.GeoDataFrame
        Container polygon GeoDataFrame with LiDAR elevation statistics added.
    """
    if geojson_path is not None:
        gdf = gpd.read_file(geojson_path)
    
    las = laspy.read(filtered_las_path)
    x = np.array(las.x)
    y = np.array(las.y)
    z = np.array(las.z)
    
    points_gdf = gpd.GeoDataFrame(
        {"z": z},
        geometry=gpd.points_from_xy(x, y),
        crs=gdf.crs
    )
    
    # Add polygon ID
    gdf = gdf.copy()
    gdf["id"] = gdf.index

    # Spatial join: assign each LiDAR point to a polygon
    joined = gpd.sjoin(
        points_gdf,
        gdf[["id", "geometry"]],
        how="inner",
        predicate="within"
    )
    
    stats = joined.groupby("id")["z"].agg(
    point_count="count",
        min_z="min",
        max_z="max",
        mean_z="mean",
        median_z="median",
        std_z="std"
    ).reset_index()

    gdf_stats = gdf.merge(stats, on="id", how="left")
    
    return gdf_stats

def crop_dsm_by_map_bounds(
    dsm_path,
    output_dsm_path,
    map_bounds
):
    """
    Crop a DSM raster using map coordinate bounds.

    The function converts map bounds into a rasterio window and writes the selected
    DSM area to a new raster file. This ensures that the DSM crop matches the
    selected RGB image area.

    Parameters
    ----------
    dsm_path : str or pathlib.Path
        Path to the input DSM GeoTIFF.
    output_dsm_path : str or pathlib.Path
        Path where the cropped DSM should be saved.
    map_bounds : dict
        Dictionary containing xmin, ymin, xmax, and ymax map coordinates.

    Returns
    -------
    str or pathlib.Path
        Path to the saved cropped DSM GeoTIFF.
    """

    with rasterio.open(dsm_path) as src:
        window = from_bounds(
            map_bounds["xmin"],
            map_bounds["ymin"],
            map_bounds["xmax"],
            map_bounds["ymax"],
            transform=src.transform
        )

        window = window.round_offsets().round_lengths()

        data = src.read(window=window)
        transform = src.window_transform(window)

        profile = src.profile.copy()
        profile.update({
            "height": data.shape[1],
            "width": data.shape[2],
            "transform": transform
        })

        with rasterio.open(output_dsm_path, "w", **profile) as dst:
            dst.write(data)

    return output_dsm_path

def crop_reference_container_geojson(
    map_bounds,
    reference_geo_json_path="data/Containers.geojson"
):
    """
    Crop reference container polygons to the selected map bounds.

    The function reads a reference GeoJSON file and keeps only polygons that
    intersect the selected bounding box. This is useful for comparing detected
    containers with reference or manually digitised containers.

    Parameters
    ----------
    map_bounds : dict
        Dictionary containing xmin, ymin, xmax, and ymax map coordinates.
    reference_geo_json_path : str or pathlib.Path, optional
        Path to the reference container GeoJSON file.

    Returns
    -------
    geopandas.GeoDataFrame
        Reference container polygons that intersect the selected map bounds.
    """
    
    reference_gdf = gpd.read_file(reference_geo_json_path)

    bbox = box(
        map_bounds["xmin"],
        map_bounds["ymin"],
        map_bounds["xmax"],
        map_bounds["ymax"],
    )

    cropped_reference_gdf = reference_gdf[
        reference_gdf.intersects(bbox)
    ]

    return cropped_reference_gdf

def add_dsm_elevation_stats(
    container_boxes_gdf,
    dsm_tiff_path,
    polygon_id_col=None,
    stats=("count", "min", "max", "mean", "median", "std"),
    prefix="dsm_"
):
    """
    Add stack_heightation statistics from a DSM TIFF to polygons.

    Parameters
    ----------
    geojson_path : str
        Path to polygon GeoJSON.
    dsm_tiff_path : str
        Path to DSM raster TIFF.
    polygon_id_col : str, optional
        Existing polygon ID column. If None, an 'id' column is created from the index.
    stats : tuple
        Zonal statistics to calculate.
    prefix : str
        Prefix added to output statistic columns.

    Returns
    -------
    GeoDataFrame
        Polygon GeoDataFrame with DSM elevation stats added.
    """
    gdf = container_boxes_gdf
    
    with rasterio.open(dsm_tiff_path) as src:
        raster_crs = src.crs
        nodata = src.nodata

    # Make sure polygons and DSM are in the same CRS
    if gdf.crs != raster_crs:
        gdf = gdf.to_crs(raster_crs)

    gdf = gdf.copy()

    if polygon_id_col is None:
        polygon_id_col = "id"
        gdf[polygon_id_col] = gdf.index

    zs = zonal_stats(
        vectors=gdf,
        raster=dsm_tiff_path,
        stats=list(stats),
        nodata=nodata,
        geojson_out=False,
        all_touched=False
    )

    stats_gdf = gdf.copy()

    for stat_name in stats:
        stats_gdf[f"{prefix}{stat_name}"] = [
            item.get(stat_name, None) for item in zs
        ]

    return stats_gdf

def add_stack_elevation(container_boxes_gdf):
    """
    Estimate container stack height using LiDAR and DSM-derived elevation values.

    The function calculates the vertical height of each detected container stack
    by subtracting a ground or ship-deck reference elevation from the LiDAR median
    elevation. Containers located on a ship are handled separately using a DSM
    threshold that identifies low-elevation water areas.

    Parameters
    ----------
    container_boxes_gdf : geopandas.GeoDataFrame
        GeoDataFrame containing detected container polygons with LiDAR and DSM
        elevation statistics.

    Returns
    -------
    geopandas.GeoDataFrame
        GeoDataFrame with added stack_height and base_height columns.
    """
    GROUND_ELEVATION = 50.0
    SHIP_DECK_ELEVATION = 62.5
    WATER_DSM_ELEVATION = 46.5#43.7#46.5
    
    base_height = SHIP_DECK_ELEVATION - GROUND_ELEVATION
    

    ship_mask = container_boxes_gdf["dsm_median"] < WATER_DSM_ELEVATION

    container_boxes_gdf["stack_height"] = (
        container_boxes_gdf["median_z"] - GROUND_ELEVATION
    )

    container_boxes_gdf.loc[ship_mask, "stack_height"] = (
        container_boxes_gdf.loc[ship_mask, "median_z"]
        - SHIP_DECK_ELEVATION
    )

    # ship_mask = container_boxes_gdf["dsm_median"] < 46.5
    container_boxes_gdf["base_height"] = 0.0
    container_boxes_gdf.loc[ship_mask, "base_height"] = base_height

    container_boxes_gdf["stack_height"] = (
        container_boxes_gdf["stack_height"].round(2)
    )

    return container_boxes_gdf

def filter_clean_container_boxes_gdf(container_boxes_gdf):
    """
    Filter detected container polygons to remove unlikely detections.

    The function applies rule-based filters based on elevation variability,
    polygon area, aspect ratio, and estimated stack height. This helps remove
    false positives such as very small objects, irregular shapes, flat objects,
    or tall non-container structures.

    Parameters
    ----------
    container_boxes_gdf : geopandas.GeoDataFrame
        GeoDataFrame containing detected container polygons and derived attributes.

    Returns
    -------
    geopandas.GeoDataFrame
        Filtered GeoDataFrame containing likely container stack detections.
    """
    container_boxes_gdf['area'] = container_boxes_gdf.area
    std_z_filter = 8.5 # to filter out very tall flood lights in image
    min_aspect_ratio = 2
    min_stack_height = 2
    
    container_boxes_gdf = container_boxes_gdf[(container_boxes_gdf['std_z'] < std_z_filter)]
    
    # container_boxes_gdf = container_boxes_gdf[(container_boxes_gdf['mean_z'] > 51)]
    
    container_boxes_gdf = container_boxes_gdf[(container_boxes_gdf['area'] > 15) & (container_boxes_gdf['area'] < 40)]
    
    container_boxes_gdf = container_boxes_gdf[(container_boxes_gdf['aspect_ratio'] > min_aspect_ratio)]
    
    container_boxes_gdf = container_boxes_gdf[(container_boxes_gdf['stack_height'] >= min_stack_height)]
    
    return container_boxes_gdf


def add_color_to_containers(
    user_selected_aoi_path,
    container_boxes_gdf,
    reference_container=False,
    brightness_threshold=130
):
    """
    Add average RGB colour values to each detected container polygon.

    The function masks the selected RGB image using each container polygon and
    calculates the mean RGB colour of valid pixels inside the polygon. For
    non-reference detections, it can also remove very dark objects using a
    brightness threshold.

    Parameters
    ----------
    user_selected_aoi_path : str or Path
        Path to the selected cropped RGB GeoTIFF.
    container_boxes_gdf : geopandas.GeoDataFrame
        GeoDataFrame containing detected container polygons.
    reference_container : bool, optional
        If True, brightness filtering is skipped.
    brightness_threshold : int or float, optional
        Minimum average brightness required to keep a detected polygon.

    Returns
    -------
    geopandas.GeoDataFrame
        GeoDataFrame with an added color column containing RGB values.
    """
    colors = []

    with rasterio.open(user_selected_aoi_path) as src:

        for geom in container_boxes_gdf.geometry:
            out_image, _ = mask(src, [geom], crop=True)

            rgb = out_image[:3]

            valid = np.all(rgb > 0, axis=0)

            if valid.any():
                mean_color = [
                    int(rgb[0][valid].mean()),
                    int(rgb[1][valid].mean()),
                    int(rgb[2][valid].mean())
                ]
            else:
                mean_color = [0, 0, 0]

            colors.append(mean_color)

    container_boxes_gdf["color"] = colors

    if not reference_container:
        mean_colors = np.array(colors)

        brightness = mean_colors.mean(axis=1)  # average of R,G,B per container

        container_boxes_gdf = container_boxes_gdf[
            brightness >= brightness_threshold
        ].copy()

    return container_boxes_gdf

def plot_image(
    container_boxes_gdf, 
    reference_containers_gdf, 
    user_selected_aoi_path, 
    image_out_path='outputs/preview_tiles/final_segmentation.jpg'
):
    """
    Plot detected and reference container polygons over the selected RGB image.

    The function displays the cropped RGB image using its real-world map extent,
    then overlays detected container polygons in red and reference container
    polygons in green. The resulting figure is saved as an image file.

    Parameters
    ----------
    container_boxes_gdf : geopandas.GeoDataFrame
        GeoDataFrame containing detected container polygons.
    reference_containers_gdf : geopandas.GeoDataFrame
        GeoDataFrame containing reference or actual container polygons.
    user_selected_aoi_path : str or Path
        Path to the selected cropped RGB GeoTIFF.
    image_out_path : str or Path, optional
        Path where the output plot image will be saved.

    Returns
    -------
    str or Path
        Path to the saved plot image.
    """
    with rasterio.open(user_selected_aoi_path) as src:
        selected_image = src.read([1, 2, 3]).transpose([1, 2, 0])
        bounds = src.bounds
    
    fig, ax = plt.subplots(figsize=(12, 12))

    # Plot raster using real-world coordinates
    ax.imshow(selected_image, extent=[
            bounds.left,
            bounds.right,
            bounds.bottom,
            bounds.top
        ])
    
    reference_containers_gdf.plot(ax=ax,
        facecolor="none",
        edgecolor="green",
        linewidth=2)

    container_boxes_gdf.plot(ax=ax,
        facecolor="none",
        edgecolor="red",
        linewidth=1)
    ax.axis('off')
    ax.set_title("Detected containers (Red) vs Actual containers (Green)")
    plt.savefig(image_out_path, dpi=150, bbox_inches='tight')
    
    return image_out_path


def add_3d_visualisation(container_boxes_gdf):
    """
    Display a 3D visualisation of detected container stacks in Streamlit.

    The function converts container polygons to WGS84 coordinates, adds base
    height values as z-coordinates, and uses PyDeck to render extruded polygons.
    The extrusion height represents the estimated stack height of each container
    detection.

    Parameters
    ----------
    container_boxes_gdf : geopandas.GeoDataFrame
        GeoDataFrame containing detected container polygons, colour values,
        base heights, stack heights, and container counts.

    Returns
    -------
    None
        The 3D visualisation is rendered directly in the Streamlit app.
    """
    container_boxes_gdf = container_boxes_gdf.to_crs("EPSG:4326")

    def add_z(poly, z):
        coords_3d = [(x, y, z) for x, y in poly.exterior.coords]
        return Polygon(coords_3d)

    container_boxes_gdf["geometry"] = container_boxes_gdf.apply(
        lambda row: add_z(row.geometry, row.base_height),
        axis=1
    )
    
    container_boxes_gdf = container_boxes_gdf.to_crs(4326)
    
    layer = pdk.Layer(
        "PolygonLayer",
        data=container_boxes_gdf,
        get_polygon="geometry.coordinates",
        get_fill_color="color",
        get_line_color=[255, 255, 255],
        get_elevation="stack_height",
        extruded=True,
        # wireframe=True,
        pickable=True,
    )
    
    centroid = container_boxes_gdf.unary_union.centroid

    view_state = pdk.ViewState(
        latitude=centroid.y,
        longitude=centroid.x,
        zoom=17,
        pitch=60,
        bearing=30,
    )
    
    deck = pdk.Deck(
        layers=[layer],
        initial_view_state=view_state,
        map_style=pdk.map_styles.LIGHT,
        # map_style="mapbox://styles/mapbox/satellite-v9",
        tooltip = {
            "html": """
            <b>Stack height:</b> {stack_height}<br>
            <b>Containers:</b> {n_containers}
            """,
            "style": {"color": "white"},
        },
        #  tooltip = {
        #     "html": """
        #     <b>Stack height:</b> {stack_height}<br>
        #     <b>Containers:</b> {n_containers}<br>
        #     <b>mean_z:</b> {mean_z}<br>
        #     <b>median_z:</b> {median_z}<br>
        #     <b>dsm_mean:</b> {dsm_mean}<br>
        #     <b>dsm_median:</b> {dsm_median}<br>
        #     <b>std_z:</b> {std_z}<br>
        #     <b>area_px:</b> {area_px}<br>
        #     <b>area:</b> {area}<br>
        #     <b>aspect_ratio:</b> {aspect_ratio}<br>
        #     <b>point_count:</b> {point_count}<br>
        #     <b>color:</b> {color}
        #     """,
        #     "style": {"color": "white"},
        # },
    )
    
    # deck.to_html("test.html")
    st.pydeck_chart(deck)
    